### ISSUE TITLE
Add this fork to HACS

### ISSUE THREAD

**Issue by erkr** [SpangleLabs/history-explorer-card#14]
The archived version from Alex is just removed from HACS. Nice if this can be offered as a replacement.

@SpangleLabs    
Just let me know when you like me to test some version.

**Comment by erkr** [comment]
I don't see releases yet, but I guess I can copy the code

**Comment by RogerSelwyn** [comment]
> Oh yeah, I don't actually know how to do that, hmm.. I'll take a look!
> 
> If you could test out the current versions (1.0.54), it should all work exactly the same as before, but be a bit easier to develop. I'm a bit worried in case something has broken, but it seems okay on my HA setup? 🤞

You also need to create proper releases, which by the look of Alex's releases is just a release with the .js file attached as an asset as well. I've done it with integrations but not with frontend items, but it should be pretty simple. People will tolerate you having a few test goes. 

Basically whenever you do a release commit, you then need to create a release using the menu which for me is to the right of the code list. I normally tag the latest commit with the same name as the release, and then release against that tag. It will lead you through that process anyway. Then I attach the relevant file. Personally I untick `Set as the latest release`, but tick `Set as a pre-release` until you are ready to go.

This guides you on adding to HACS, you will need to remove Alex's repository, because you can't have duplicates - https://hacs.xyz/docs/publish/include/. It will take some months to make it in, since they only process 1/2 dozen requests a week. Looks like they are working upon November/Decembers requests.

**Comment by KingTeppic** [comment]
For others reading this, it's worth noting here that the manual installation process is pretty straightforward, and this is a truly amazing card.

**Comment by erkr** [comment]
The archive should be renovated already by HACS:
![image](https://github.com/SpangleLabs/history-explorer-card/assets/4363599/90c8f2c9-80cf-4043-aadc-72e9d073369f)

**Comment by erkr** [comment]
@RogerSelwyn @KingTeppic want to join a team reviving this card?!
I'm in for testing. I have a lot of programming experience but none in the web/js area

**Comment by RogerSelwyn** [comment]
I work almost entirely on backend integrations. I'm happy to test in my environment, but not really into debugging through frontend components, I already spend more time than my wife would like on backend python.

Thanks for the offer though.

**Comment by SpangleLabs** [comment]
I've made some github releases from the tags (and pushed the tags, oops).
I'm hoping to put together a github automation to do that in future too.

I'll have to figure out the HACS PR tomorrow, hopefully

**Comment by marriotb** [comment]
Thank you, @SpangleLabs , for reviving this!!
I followed the manual installation process (as @KingTeppic says, it's straightforward:-) and all my lovely graphs re-appeared.

I'll give it some more testing time over the next few days, but so far all is working beautifully!

Thanks again, Brian

**Comment by Protoncek** [comment]
A big thanks from me, too! I've been worried more and more when this amazing card will stop functioning... I'm so used to have days, weeks... available, and that i can mark a detail and see... i just can't imagine HA without this card anymore.
Now i can "sleep again"...

**Comment by erkr** [comment]
I have your v1.0.54 installed now.    First impression is that it works the same 👍

**Comment by SpangleLabs** [comment]
Awesome!
Okay, I think that PR is filed with HACS now: https://github.com/hacs/default/pull/2501
Apologies I've not had as much time to work on this this weekend as I had hoped. (I blame solar activity, in various forms!)

**Comment by erkr** [comment]
I have used it for some time now and it's stable and functionally equal to the original. So your plumbing under the hood worked out ok 👍

**Comment by FlexxFR** [comment]
Just want to say thanks @SpangleLabs for this card.
Can't find it yet via HACS but will proceed with manual install.

**Comment by RogerSelwyn** [comment]
It will take months to get onto HACS default.

**Comment by FlexxFR** [comment]
oh, okay. No problem  for now. It works fine.
Maybe it's worth updating the installation description, to point out the manual repository option. 

Happy that it works again. This is trully a great card.

**Comment by duncansmart** [comment]
Kudos to @SpangleLabs for taking this on 👍. For those who forgot how to manually add repositories to HACS (i.e me 2 minutes ago 😉) - a quick refresher:

![image](https://github.com/SpangleLabs/history-explorer-card/assets/576343/b426ab1a-2271-46fb-9b0b-027f4b54aff5)

**Comment by erkr** [comment]
Congratulations, just downloaded the card from the HACS store 🎉

**Comment by SpangleLabs** [comment]
Oh, how? I don't think it's been added to the HACS repositories yet? https://github.com/hacs/default/pull/2501 isn't yet landed

(Apologies btw for no updates and features on this yet, have had a busy time! but keeping an eye on emails and such. Thanks all for the thanks!)

**Comment by erkr** [comment]
I did a fresh install and when I wanted to add the custom tree repository, HACS mentioned it was part of the store

**Comment by Wright55** [comment]
Deleted old version restarted HA and downloaded new version, installed perfectly.
Thanks for reviving this essential element of HA

**Comment by bakerkj** [comment]
@SpangleLabs, thank you for keeping this project going!

**Comment by GerhardKreuzer** [comment]
.. sorry but in the actual HA version there is no 'Lovelace' type to select....

**Comment by chomats** [comment]
It's not work : 
I have an error : <Integration SpangleLabs/history-explorer-card> Repository structure for v1.0.54 is not compliant

**Comment by elGamo** [comment]
> .. sorry but in the actual HA version there is no 'Lovelace' type to select....

Choose "Dashboard" as type.
