### ISSUE TITLE
Drop Down menu with Home Assistant Android App 

### ISSUE THREAD

**Issue by Cook23** [SpangleLabs/history-explorer-card#15]
Hello,

1st thanks to revive this very useful piece of software

An old issue is the drop down list to select entities don't works with Home Assistant Android App. If you can have a look on this problem it should be great.

Another point, the storage of analog data in HA database is really not optimal. I came from industrial automation and the usual rule to limit volume of analog stored data is to apply : low pass 1st order filter then deadband then data storage rate limitation with max (ex 1 by min to limit volume) and min (ex 1 by hour to ensure a minimum regular storage rate of quite invariant variables). I do this to all sensor variable in a node red sheet but it's really inconvenient. I didn't find easier way and it seems nobody explore this way. 

With this reduction of data volume, history explorer card is very very fast. Scroll and zoom are instant.

**Comment by KingTeppic** [comment]
You mean you can't download CSV data? In other respects the drop down seems too work fine for me through the app (Android).
I assumed the downloads failing was limitation of the HA app, not anything to do with this card - but that is nothing other than wild speculation...

**Comment by Cook23** [comment]
No the basic drop down menu to add entities. Works perfectly with chrome and Firefox windows. Works with chrome android. Works with fully kiosk android only with spoofed identity chrome. Don't works at all with Firefox android (original developer says it's normal). Don't works with Home Assistant app. But I remember I saw it working one time in one of my devices and never again. So maybe it's something specific to my devices. I will try to change the keyboard back to Google one.

**Comment by Cook23** [comment]
![Uploading Screenshot_20240515_025230_Fully Kiosk Browser.jpg…]()

**Comment by Cook23** [comment]
![Screenshot_20240515_025230_Fully Kiosk Browser](https://github.com/SpangleLabs/history-explorer-card/assets/46299399/c7d2fa18-5da5-4836-a6b0-a939acd9bb4c)

**Comment by Cook23** [comment]
Now it's works. Don't know why.
