### ISSUE TITLE
Adjust width of the graph to full screen

### ISSUE THREAD

**Issue by Vendo233** [SpangleLabs/history-explorer-card#25]
This might be some elemntar HA knowledge so please apology. I would like to stretch the graph to full width of the screen. Is it possible?

![image](https://github.com/user-attachments/assets/84c4796b-2f1f-4b99-a66b-e3c90a2fbda2)

**Comment by KingTeppic** [comment]
Easy, you just want to change the view type of that dashboard to 'Sidebar'.

**Comment by Protoncek** [comment]
...or to "1 panel", then you create vertical stack and stack your cards there...

**Comment by Vendo233** [comment]
> Easy, you just want to change the view type of that dashboard to 'Sidebar'.

Worked! learned something new today, thank you

![image](https://github.com/user-attachments/assets/53593269-e456-4d29-b112-eb5d0f158f9f)

**Comment by Vendo233** [comment]
> ...or to "panel(1 card)", then you create vertical stack and stack your cards there...

this suggestion works even better, thank you

![image](https://github.com/user-attachments/assets/4371eb11-1d54-4356-9b6c-aeab74e7c1f6)
