### ISSUE TITLE
Can a card be saved to all access devices?

### ISSUE THREAD

**Issue by composure1075** [SpangleLabs/history-explorer-card#27]
I'm newer to Home Assistant, so I might not be using the correct terms. I created a card on my Android companion app. It doesn't appear when I access HA from my desktop or laptop. I usually use the local URL to access from my desktop and laptop. Is it possible to see the same card on all of these devices? If so, how is it done?

**Comment by KingTeppic** [comment]
This is a core part of the way history explorer works. If you add graphs to the card using the 'Type to search for an entity to add' box the result will indeed be device specific. You are also quite limited in what you can do with the graph.

To really unlock the power of this card you need to get your hands dirty and define the charts including entities directly in the yaml. Cards created this way will look the same across devices.
