### ISSUE TITLE
CARD vanished from HACS ?

### ISSUE THREAD

**Issue by yocup** [SpangleLabs/history-explorer-card#30]
He SpangleLabs.

What a fantastic card. 
.. until it suddenly vanished today!!

After finding your great history-explorer-card again via [this request of mine](https://community.home-assistant.io/t/interactive-history-with-statistic-graph-cards/783043), I started installing it manually via www, and adding a resource, but it wouldn't show up when trying to add it in the dashboard, no luck. I then tried adding it via HACS / custom repositories, but got an error message. When trying to find it again on HACS, it suddenly showed up as under spanglelabs/history-explorer-card!

Yeah, I installed it and it worked fine right away.

I spend all day creating a long custum card when around 11 PM home assistant suddenly restarted and after restart told me, that the there is no integration named history-explorer-card anymore. 

Looking in the filebrowser showed me it had vanished.

So I tried installing it via the manual method again, no luck. And when adding the URL [https://github.com/SpangleLabs/history-explorer-card/](https://github.com/SpangleLabs/history-explorer-card/) to custom repositories I got the following error:

**<Integration SpangleLabs/history-explorer-card> Repository structure for v1.0.54 is not compliant**

What am I doing wrong. Happyly I saved my .yaml from today, but I would love to use it.

Help appreciated.
:astonished:

Kind regards,
yocup

**Comment by yocup** [comment]
..was able to Install it again via custom reps.

I made the error adding it as an integration instead of as dashboard.
Thanks to nickrout on the HA community forum, who reminded me. :)

**Still interested to know why it vanished from the official HACS.**

**Comment by ovizii** [comment]
Do you mind sharing how you added it? What is the URL of the custom repository?
